apiVersion: v1
kind: Service
metadata:
  name: gcplb
  labels:
    app: tea
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tea
  clusterIP: 10.254.0.11
  type: LoadBalancer

